# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: F*ck feelings
email: ademilsonft@outlook.com
description: "Esse é um blog com intuito de armazenar experiências e desejos."

#Config
baseurl: "https://morrer.com.br" # the subpath of your site, e.g. /blog
url: "https://morrer.com.br" # the base hostname & protocol for your site

# mostrando somente o título
permalink: /:title/

# PAGINATION
paginate: 4
paginate_path: "/:num/"

#Socials
twitter_username: ftonato
github_username:  ftonato

# Build settings
##markdown: kramdown

gems:
  - jekyll-paginate
